### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by desicruizer** [Jamonek/Robinhood#134]
First off... thank you for putting this together.  I've using your code to pull option history and am now getting the following when attempting to run the program.   It worked fine last month as I had used it many times and I tried executing the options export script and am now getting this.

Traceback (most recent call last):
  File "csv-options-export.py", line 46, in <module>
    logged_in = robinhood.login(username=username, password=password)
  File "/Users/Owner/Downloads/robinhood-to-csv-master-2/Robinhood.py", line 81, in login
    res = res.json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by justin-pierce** [comment]
Robinhood has just changed their login api it seems -- maybe related to your issues. See https://github.com/sanko/Robinhood/issues/86

**Comment by desicruizer** [comment]
Thanks for the response.  So it seems without the new API this will no longer work until updated?

Can we expect this update, anytime in your code enhancements?

Again... thank you for all that you've done!

**Comment by desicruizer** [comment]
resolved...  thank you :)

See for my resolution ..... 

https://github.com/Jamonek/Robinhood/issues/135#issuecomment-420724991
