### ISSUE TITLE
object has no attribute 'upper'

### ISSUE THREAD

**Issue by HMSS013** [Jamonek/Robinhood#166]
This error started occurring today when using the 'l' list all function:

Traceback (most recent call last):
  File "./shell.py", line 383, in <module>
    RobinhoodShell().cmdloop()
  File "/usr/lib64/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "./shell.py", line 76, in do_l
    raw_data = self.trader.quotes_data(symbols)
  File "/home/HMSS013/.dropbox-shared/Dropbox/Public/Market Service/Shell/Robinhood.py", line 257, in quotes_data
    raise NameError('Invalid Symbols: ' + ",".join(stocks)).upper() #TODO: custom exception
AttributeError: 'exceptions.NameError' object has no attribute 'upper'

**Comment by HMSS013** [comment]
closing as this is not related to this version
