### ISSUE TITLE
HTTP Error 400 Client Error: Bad Request for url

### ISSUE THREAD

**Issue by tdewhurst** [Jamonek/Robinhood#170]
I am having an issue when trying to set a stop loss on a stock that is giving me an HTTP error. I've reviewed the previous issues and PR that have submitted, but haven't been able to find a solution. Is anyone experience similar issues or have a fix?

Code:
Robinhood.place_stop_loss_sell_order(symbol=df['ticker'][i],time_in_force='GTC',stop_price=(df['buy_price'][i]*.985),quantity=df['quantity'][i])

Traceback (most recent call last):
  File "C:/Users/frmtdewh/Desktop/Python/API/API - New.py", line 166, in <module>
    reset_stop()
  File "C:/Users/frmtdewh/Desktop/Python/API/API - New.py", line 156, in reset_stop
    rh.place_stop_loss_sell_order(symbol=df['ticker'][i],time_in_force='GTC',stop_price=(df['buy_price'][i]*.985),quantity=df['quantity'][i])
  File "C:\Users\frmtdewh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\Robinhood\Robinhood.py", line 1178, in place_stop_loss_sell_order
    quantity=quantity))
  File "C:\Users\frmtdewh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\Robinhood\Robinhood.py", line 1350, in submit_order
    res.raise_for_status()
  File "C:\Users\frmtdewh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/orders/

**Comment by tdewhurst** [comment]
I've tried various different methods of placing stop orders but have had no luck. Is there an authentication that I am missing in my code? I am logging into the Robinhood account (rh.login(username='username',password='password')) and able to see my positions, previous orders, holdings, etc., but I am unable to place stop orders.

**Comment by tdewhurst** [comment]
Discovered the issue was actually that Robinhood couldn't handle more than two significant figures in the stop_price. Just needed to round the number. Closing this ticket.

**Comment by DerekKingsley** [comment]
round(stop_price,2) got your request working? I've discovered run into a similar issue using place_order. After seeing this thought rounding the float to 2 decimals would work but didn't seem to help.
