### ISSUE TITLE
AttributeError when calling place_buy_order()

### ISSUE THREAD

**Issue by omenyayl** [Jamonek/Robinhood#36]
buy_order = rb.place_buy_order(gevo_stock,  1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python2.7/site-packages/Robinhood/Robinhood.py", line 744, in place_buy_order
    return self.place_order(instrument, quantity, bid_price, transaction)
  File "/home/user/.local/lib/python2.7/site-packages/Robinhood/Robinhood.py", line 705, in place_order
    'side': transaction.name.lower(),
AttributeError: 'Transaction' object has no attribute 'name'

**Comment by omenyayl** [comment]
Fixed by using Python3.

**Comment by nlowell11** [comment]
For those who want to stay on Python 2, I was able to fix the same issue using this version of enum:
https://pypi.python.org/pypi/enum34
